package datamigrate

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"time"
)

// QuarantineTable holds rows that could not be copied, with reasons.
// Nothing is ever silently dropped: every skipped row lands here (PG side)
// and in the run Summary, so a human can fix and re-run.
const QuarantineTable = "_migration_quarantine"

// Quarantined is one skipped row.
type Quarantined struct {
	Table  string
	Row    map[string]string
	Reason string
}

// EnsureQuarantine creates the quarantine table if missing.
func EnsureQuarantine(ctx context.Context, e execer, tableName ...string) error {
	name := QuarantineTable
	if len(tableName) > 0 && tableName[0] != "" {
		name = tableName[0]
	}
	_, err := e.ExecContext(ctx, fmt.Sprintf(`CREATE TABLE IF NOT EXISTS "%s" (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		table_name TEXT NOT NULL,
		row_json TEXT NOT NULL,
		reason TEXT NOT NULL,
		created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`, name))
	return err
}

// RecordQuarantine stores one skipped row. Table name is fixed to avoid
// SQL injection (only the constant or an internal override is used).
// Re-runs are idempotent: an identical (table, row, reason) entry is stored
// once. Reports whether a new row was inserted.
func RecordQuarantine(ctx context.Context, e execer, q Quarantined) (bool, error) {
	raw, err := json.Marshal(q.Row)
	if err != nil {
		raw = []byte("{}")
	}
	res, err := e.ExecContext(ctx,
		`INSERT INTO "`+QuarantineTable+`" (table_name, row_json, reason, created_at)
		 SELECT $1, $2, $3, $4 WHERE NOT EXISTS
		 (SELECT 1 FROM "`+QuarantineTable+`" WHERE table_name=$1 AND row_json=$2 AND reason=$3)`,
		q.Table, string(raw), q.Reason, time.Now().UTC())
	if err != nil {
		return false, err
	}
	n, _ := res.RowsAffected()
	return n == 1, nil
}

type execer interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
}
