#!/usr/bin/env bash
# dump-schema.sh — regenerate db/schema.sql from all migrations.
# The snapshot is a READ-ONLY reference (one file, full CREATE TABLEs).
# Source of truth stays db/migrations/ (append-only); rerun after each migration.
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"
TMP="$(mktemp /tmp/schema-XXXXXX.db)"
trap 'rm -f "$TMP"' EXIT

go run ./scripts/dumpschema "$ROOT/db/migrations" "$TMP"

{
  echo "-- GENERATED by scripts/dump-schema.sh — do not hand-edit."
  echo "-- Regenerate: ./scripts/dump-schema.sh (after any new migration)."
  echo ""
  sqlite3 "$TMP" "SELECT sql || ';' FROM sqlite_master WHERE type='table' AND name NOT IN ('goose_db_version','sqlite_sequence') AND sql IS NOT NULL ORDER BY name;"
  echo ""
  sqlite3 "$TMP" "SELECT sql || ';' FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name;"
  echo ""
  sqlite3 "$TMP" "SELECT sql || ';' FROM sqlite_master WHERE type='trigger' AND sql IS NOT NULL ORDER BY name;"
} > "$ROOT/db/schema.sql"

# Self-checks: our tables present, dropped ones absent.
grep -q "CREATE TABLE tenant_accounting_settings" "$ROOT/db/schema.sql"
for t in i18n_keys notifications_preferences revoked_refresh_tokens provider_poll_state route_constraints offline_sync_log audit_events telemetry_events; do
  if grep -q "CREATE TABLE $t" "$ROOT/db/schema.sql"; then echo "STALE TABLE IN SNAPSHOT: $t"; exit 1; fi
done
echo "db/schema.sql regenerated: $(grep -c '^CREATE TABLE' "$ROOT/db/schema.sql") tables"
