package handlers

import (
	"context"
	"database/sql"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/pressly/goose/v3"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	_ "modernc.org/sqlite"

	"transport-app/internal/geofence/domain"
	"transport-app/internal/shared"
)

// handlerTestDB creates an in-memory SQLite DB with all migrations applied.
func handlerTestDB(t *testing.T) *sql.DB {
	t.Helper()
	cwd, _ := os.Getwd()
	if filepath.Base(cwd) == "handlers" {
		t.Chdir("../..")
	}
	name := fmt.Sprintf("test_handlers_%s_%d", strings.ReplaceAll(t.Name(), "/", "_"), time.Now().UnixNano())
	db, err := sql.Open("sqlite", "file:"+name+"?mode=memory&cache=shared&_pragma=journal_mode(WAL)")
	require.NoError(t, err)
	_ = goose.SetDialect("sqlite")
	require.NoError(t, goose.Up(db, "db/migrations"))
	t.Cleanup(func() { _ = db.Close() })
	return db
}

// seedDeliveredTrip inserts the booking/trip/detention rows a completion test
// needs. tripID/bookingID/customerID are generated by the caller.
func seedDeliveredTrip(t *testing.T, db *sql.DB, tripID, bookingID string) {
	t.Helper()
	_, err := db.Exec(`INSERT INTO customers (id, name, company, phone) VALUES ('c1', 'Acme', 'Acme Pvt Ltd', '9988776655')`)
	require.NoError(t, err)
	_, err = db.Exec(`INSERT INTO routes (id, source, destination, distance, estimated_hours, standard_fare)
		VALUES ('r1', 'Bengaluru', 'Mysuru', 145, 3, 25000)`)
	require.NoError(t, err)
	_, err = db.Exec(`INSERT INTO bookings (id, booking_number, customer_id, pickup_date, route_id, vehicle_type, price, status)
		VALUES (?, 'BK-001', 'c1', '2026-08-19 09:00:00', 'r1', 'truck', 25000, 'confirmed')`, bookingID)
	require.NoError(t, err)
	_, err = db.Exec(`INSERT INTO trips (id, trip_number, booking_id, route_id, departure_time, status)
		VALUES (?, 'TRIP-001', ?, 'r1', '2026-08-19 09:00:00', 'delivered')`, tripID, bookingID)
	require.NoError(t, err)
	// GST enabled at 18% so the pricing resolver re-derives the booking tax.
	_, err = db.Exec(`INSERT INTO company_settings
		(id, company_name, currency, timezone, gst_enabled, gst_rate)
		VALUES (1, 'Avandab', 'INR', 'Asia/Kolkata', 1, 18)
		ON CONFLICT(id) DO UPDATE SET gst_enabled = 1, gst_rate = 18`)
	require.NoError(t, err)
	_, err = db.Exec(`INSERT INTO geofences
		(id, tenant_id, name, kind, shape, center_lat, center_lng, radius_m, priority, is_active)
		VALUES ('g1', '1', 'Mysuru Depot', 'depot', 'circle', 12.3, 76.6, 500, 10, 1)`)
	require.NoError(t, err)
}

// seedClosedDetention inserts a closed detention row for the trip.
func seedClosedDetention(t *testing.T, db *sql.DB, tripID, detentionID string, amount float64) {
	t.Helper()
	_, err := db.Exec(`INSERT INTO trip_detentions
		(id, tenant_id, trip_id, vehicle_id, geofence_id, zone_kind, entered_at, exited_at,
		 dwell_seconds, free_seconds, billable_seconds, rate_per_hour, amount, status)
		VALUES (?, '1', ?, NULL, 'g1', 'pickup', '2026-08-19 10:00:00', '2026-08-19 12:00:00',
		        7200, 1800, 5400, 10, ?, 'closed')`, detentionID, tripID, amount)
	require.NoError(t, err)
}

// completeTripRequest builds the chi context request the CompleteTrip handler
// receives from the router.
func completeTripRequest(t *testing.T, tripID string) *http.Request {
	t.Helper()
	r := httptest.NewRequest(http.MethodPost, "/trips/"+tripID+"/complete", nil)
	ctx := chi.NewRouteContext()
	ctx.URLParams.Add("id", tripID)
	rctx := context.WithValue(r.Context(), chi.RouteCtxKey, ctx)
	rctx = shared.ContextWithTenantID(rctx, shared.DefaultTenant)
	return r.WithContext(rctx)
}

func TestTripHandlers_CompleteTrip_AttachesClosedDetentions(t *testing.T) {
	db := handlerTestDB(t)
	seedDeliveredTrip(t, db, "t1", "b1")
	seedClosedDetention(t, db, "t1", "d1", 15.00)

	h := &TripHandlers{App: &App{DB: db}}
	w := httptest.NewRecorder()
	h.CompleteTrip(w, completeTripRequest(t, "t1"))
	assert.Equal(t, http.StatusSeeOther, w.Code)

	// Trip completed.
	var status string
	require.NoError(t, db.QueryRow(`SELECT status FROM trips WHERE id = 't1'`).Scan(&status))
	assert.Equal(t, "completed", status)

	// Invoice generated with the detention line (auto-attach).
	var subtotal, tax, total float64
	var invoiceCount int
	require.NoError(t, db.QueryRow(`SELECT count(*) FROM invoices WHERE booking_id = 'b1'`).Scan(&invoiceCount))
	assert.Equal(t, 1, invoiceCount)
	require.NoError(t, db.QueryRow(`SELECT subtotal, tax, total FROM invoices WHERE booking_id = 'b1'`).Scan(&subtotal, &tax, &total))
	// Subtotal = booking freight + detention line; GST applies to the freight
	// subtotal only (spec silent on detention taxation — resolved from the
	// company settings at 18%).
	assert.InDelta(t, 25000+15.00, subtotal, 0.01)
	assert.InDelta(t, 4500.0, tax, 0.01)
	assert.InDelta(t, subtotal+tax, total, 0.01)

	// Detention line item persisted with the detention ref, freight preserved.
	var lineCount, detentionLines, freightLines int
	require.NoError(t, db.QueryRow(`SELECT count(*) FROM invoice_line_items WHERE invoice_id = (SELECT id FROM invoices WHERE booking_id = 'b1')`).Scan(&lineCount))
	require.NoError(t, db.QueryRow(`SELECT count(*) FROM invoice_line_items WHERE line_type = 'detention' AND ref_id = 'd1'`).Scan(&detentionLines))
	require.NoError(t, db.QueryRow(`SELECT count(*) FROM invoice_line_items WHERE line_type = 'freight'`).Scan(&freightLines))
	assert.Equal(t, 2, lineCount)
	assert.Equal(t, 1, detentionLines)
	assert.Equal(t, 1, freightLines)

	// Detention flipped to attached.
	var detStatus string
	require.NoError(t, db.QueryRow(`SELECT status FROM trip_detentions WHERE id = 'd1'`).Scan(&detStatus))
	assert.Equal(t, domain.DetentionAttached, detStatus)
}

func TestTripHandlers_CompleteTrip_PaidInvoiceGuard(t *testing.T) {
	db := handlerTestDB(t)
	seedDeliveredTrip(t, db, "t1", "b1")
	seedClosedDetention(t, db, "t1", "d1", 15.00)

	// A paid invoice already exists for the booking — completion must NOT
	// mutate it, and the detention must stay closed for manual handling.
	_, err := db.Exec(`INSERT INTO invoices
		(id, invoice_number, booking_id, customer_id, trip_id, subtotal, tax, discount, total, payment_status, status, paid_amount)
		VALUES ('inv1', 'INV-001', 'b1', 'c1', 't1', 25000, 4500, 0, 29500, 'paid', 'outstanding', 29500)`)
	require.NoError(t, err)

	h := &TripHandlers{App: &App{DB: db}}
	w := httptest.NewRecorder()
	h.CompleteTrip(w, completeTripRequest(t, "t1"))
	assert.Equal(t, http.StatusSeeOther, w.Code)

	var lineCount int
	require.NoError(t, db.QueryRow(`SELECT count(*) FROM invoice_line_items WHERE invoice_id = 'inv1'`).Scan(&lineCount))
	assert.Equal(t, 0, lineCount, "paid invoice must not gain detention lines")

	var detStatus string
	require.NoError(t, db.QueryRow(`SELECT status FROM trip_detentions WHERE id = 'd1'`).Scan(&detStatus))
	assert.Equal(t, domain.DetentionClosed, detStatus, "detention stays closed when the invoice is already paid")
}
